#!/usr/bin/env bash
# ============================================================
# create-dev-users.sh
# Creates local development auth users via the Supabase Admin API,
# then reseeds the database.
#
# Usage: ./supabase/scripts/create-dev-users.sh
#
# Run this AFTER: npx supabase db reset
# (db reset wipes auth.users; this script recreates them and seeds)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
CREDENTIALS_FILE="${ROOT_DIR}/.demo-credentials.local"

load_env_file() {
  local file="$1"
  if [[ -f "$file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$file"
    set +a
  fi
}

load_env_file "${ROOT_DIR}/.env"
load_env_file "${ROOT_DIR}/.env.local"

SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-http://127.0.0.1:4201}"
SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-}"

if [[ -z "${SERVICE_ROLE_KEY}" ]]; then
  echo "ERROR: SUPABASE_SERVICE_ROLE_KEY is not set."
  echo "Set it in .env.local or your shell env, then rerun this script."
  exit 1
fi

DEFAULT_PASSWORD="${CHURCHCORE_OPS_DEV_PASSWORD:-$(python3 - <<'PY'
import secrets
import string

alphabet = string.ascii_letters + string.digits
password = "".join(secrets.choice(alphabet) for _ in range(18)) + "!"
print(password)
PY
)}"

create_user() {
  local email="$1"
  local result
  result=$(curl -s -X POST "${SUPABASE_URL}/auth/v1/admin/users" \
    -H "apikey: ${SERVICE_ROLE_KEY}" \
    -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
    -H "Content-Type: application/json" \
    -d "{\"email\": \"${email}\", \"password\": \"${DEFAULT_PASSWORD}\", \"email_confirm\": true}")

  local id
  id=$(echo "$result" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('id','ERROR: ' + str(d.get('msg', d.get('error', 'unknown')))))" 2>/dev/null || echo "ERROR: parse failed")

  if [[ "$id" == ERROR* ]]; then
    if [[ "$result" == *"already been registered"* ]]; then
      local user_id
      user_id=$(curl -s "${SUPABASE_URL}/auth/v1/admin/users?page=1&per_page=1000" \
        -H "apikey: ${SERVICE_ROLE_KEY}" \
        -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" |
        python3 -c "import json,sys; email='${email}'; d=json.load(sys.stdin); print(next((u.get('id','') for u in d.get('users', []) if u.get('email') == email), ''))")

      if [[ -z "$user_id" ]]; then
        echo "  ✗  ${email}: already exists but could not be loaded for password reset"
        return 1
      fi

      result=$(curl -s -X PUT "${SUPABASE_URL}/auth/v1/admin/users/${user_id}" \
        -H "apikey: ${SERVICE_ROLE_KEY}" \
        -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"password\": \"${DEFAULT_PASSWORD}\", \"email_confirm\": true}")

      id=$(echo "$result" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('id','ERROR: ' + str(d.get('msg', d.get('error', 'unknown')))))" 2>/dev/null || echo "ERROR: parse failed")
      if [[ "$id" == ERROR* ]]; then
        echo "  ✗  ${email}: password reset failed: ${id}"
        return 1
      fi

      echo "  ⚠  ${email}: already exists, password reset"
      return 0
    fi

    echo "  ✗  ${email}: ${id}"
    return 1
  else
    echo "  ✓  ${email} → ${id}"
  fi
}

echo ""
echo "Creating dev auth users..."
create_user "sarah@churchcoreops.app"
create_user "david@graceharbor.church"
create_user "olivia@graceharbor.church"
create_user "miriam@graceharbor.church"
create_user "robert@graceharbor.church"

echo ""
echo "Running seed..."
seed_output="$(npx supabase db query --file "${SCRIPT_DIR}/../seed.sql" 2>&1)" || {
  echo "${seed_output}"
  exit 1
}
echo "${seed_output}" | grep -E "NOTICE|ERROR|error" || true

cat > "${CREDENTIALS_FILE}" <<EOF
# Local demo credentials generated by supabase/scripts/create-dev-users.sh
# This file is gitignored and safe to keep only on your machine.
CHURCHCORE_OPS_DEV_PASSWORD=${DEFAULT_PASSWORD}
CHURCHCORE_OPS_DEMO_ADMIN_EMAIL=sarah@churchcoreops.app
CHURCHCORE_OPS_DEMO_MEMBER_EMAIL=david@graceharbor.church
CHURCHCORE_OPS_DEMO_SECRETARY_EMAIL=olivia@graceharbor.church
CHURCHCORE_OPS_DEMO_PASTOR_EMAIL=miriam@graceharbor.church
CHURCHCORE_OPS_DEMO_MINISTRY_LEADER_EMAIL=robert@graceharbor.church
EOF
chmod 600 "${CREDENTIALS_FILE}"

echo ""
echo "Done. Local dev accounts ready:"
echo "  sarah@churchcoreops.app    / ${DEFAULT_PASSWORD}  (church-admin + platform-admin)"
echo "  david@graceharbor.church    / ${DEFAULT_PASSWORD}  (member)"
echo "  olivia@graceharbor.church   / ${DEFAULT_PASSWORD}  (secretary / office admin)"
echo "  miriam@graceharbor.church   / ${DEFAULT_PASSWORD}  (pastor / elder)"
echo "  robert@graceharbor.church   / ${DEFAULT_PASSWORD}  (ministry leader)"
echo ""
echo "Saved local demo credentials to:"
echo "  ${CREDENTIALS_FILE}"
echo ""
echo "App:      http://localhost:4200/sign-in"
echo "Studio:   http://127.0.0.1:4204"
echo "Mailpit:  http://127.0.0.1:4205"
